# Generated by Django 3.1.2 on 2020-10-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('_idPacientes', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Dni', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Estrato', models.CharField(max_length=1)),
                ('correo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
